-- CREATE THE STOCKS TABLE
CREATE TABLE pythor_stocks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    stock_name VARCHAR(50) NOT NULL,
    stock_value INT NOT NULL,     
    last_updated DATETIME,            
    next_update DATETIME              
);

-- INSERT STARTING VALUES, YOU CAN CREATE MORE OR REMOVE
INSERT INTO pythor_stocks (stock_name, stock_value, last_updated, next_update) VALUES
('Train', 100, NOW(), DATE_ADD(NOW(), INTERVAL 1 DAY)),
('Oil', 100, NOW(), DATE_ADD(NOW(), INTERVAL 1 DAY)),
('Spices', 100, NOW(), DATE_ADD(NOW(), INTERVAL 1 DAY)),
('Gold', 100, NOW(), DATE_ADD(NOW(), INTERVAL 1 DAY));

-- A COMMAND TO ENABLE EVENT TO CHANGE STOCK VALUE (YOU CAN RUN THE CODE WITHOUT IT TO DISABLE THE EVENT) 
SET GLOBAL event_scheduler = ON;

-- CREATE AN EVENT TO CHANGE STOCK VALUES EVERY DAY (YOU CAN CHANGE THAT)
DELIMITER $$

CREATE EVENT update_stock_values
ON SCHEDULE EVERY 1 DAY -- CHANGE INTERVAL 1 DAY TO ANY NUMBER YOU WANT
STARTS CURRENT_TIMESTAMP + INTERVAL 1 DAY
DO
BEGIN
    UPDATE pythor_stocks
    SET stock_value = LEAST(200, GREATEST(50, stock_value + FLOOR(RAND() * 100 - 50))),
        last_updated = NOW(), 
        next_update = DATE_ADD(NOW(), INTERVAL 1 DAY); 
END$$

DELIMITER ;

-- A COMMAND TO CHECK IF THE EVENT SET UP CORRECTLY
SHOW EVENTS